import type { Request } from "./request-types"

export const MOCK_REQUESTS: Request[] = [
  {
    id: "1",
    title: "Request for 10 Dell Laptops",
    description: "Need 10 new laptops for the development team expansion",
    type: "inventory",
    status: "pending",
    priority: "high",
    requestedBy: "John Doe",
    requestedByEmail: "john@yomi.com",
    assignedTo: "Admin User",
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
    itemName: "Dell Laptop XPS 15",
    quantity: 10,
  },
  {
    id: "2",
    title: "Network Switch Replacement",
    description: "Main office switch is failing, need immediate replacement",
    type: "maintenance",
    status: "approved",
    priority: "urgent",
    requestedBy: "Jane Smith",
    requestedByEmail: "jane@yomi.com",
    assignedTo: "Manager User",
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-01-19"),
    itemName: "Cisco Switch 24-Port",
    quantity: 1,
  },
  {
    id: "3",
    title: "Software License Renewal",
    description: "Adobe Creative Cloud licenses expiring next month",
    type: "inventory",
    status: "completed",
    priority: "medium",
    requestedBy: "Mike Johnson",
    requestedByEmail: "mike@yomi.com",
    assignedTo: "Admin User",
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-17"),
    itemName: "Adobe Creative Cloud",
    quantity: 30,
  },
  {
    id: "4",
    title: "Printer Not Working",
    description: "Office printer on 3rd floor is not responding",
    type: "support",
    status: "pending",
    priority: "low",
    requestedBy: "Sarah Williams",
    requestedByEmail: "sarah@yomi.com",
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
  },
  {
    id: "5",
    title: "Additional Monitors Request",
    description: "Request for 5 additional monitors for the design team",
    type: "inventory",
    status: "rejected",
    priority: "medium",
    requestedBy: "Tom Brown",
    requestedByEmail: "tom@yomi.com",
    assignedTo: "Manager User",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-12"),
    itemName: 'Samsung Monitor 27"',
    quantity: 5,
    notes: "Budget constraints - will revisit next quarter",
  },
]
