export const mockTeamMembers: any[] = [
  {
    id: "1",
    name: "Viktor Cesar",
    email: "Viktorcesar66@gmail.com",
    role: "admin",
    department: "TI",
    permissions: {
      inventory: true,
      calendar: true,
      finance: true,
      requests: true,
      communication: true,
    },
    joinedDate: "2024-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "João Silva",
    email: "joao.silva@email.com",
    role: "manager",
    department: "Operações",
    permissions: {
      inventory: true,
      calendar: true,
      finance: false,
      requests: true,
      communication: true,
    },
    joinedDate: "2024-02-20",
    status: "active",
  },
  {
    id: "3",
    name: "Maria Santos",
    email: "maria.santos@email.com",
    role: "member",
    department: "Vendas",
    permissions: {
      inventory: true,
      calendar: true,
      finance: false,
      requests: true,
      communication: true,
    },
    joinedDate: "2024-03-10",
    status: "active",
  },
]
